added test cases for Book and Category entities on each layer
knyazkyylubomir/online-book-store pull request #11
Opened 2023-10-11 15:09 UTC by knyazkyylubomir

![test coverage result](https://github.com/knyazkyylubomir/online-book-store/assets/122437478/4ec458e1-f2fc-4714-953e-e4e88b658efe)

2023-10-11 20:33 UTC, Ivan95kos requested changes
Good job overall!

2023-10-11 20:33 UTC, Ivan95kos commented on src/test/java/org/project/name/online/book/store/controller/BookControllerTest.java
> +class BookControllerTest {
```suggestion
class BookControllerIntegrationTest {
```

2023-10-11 20:33 UTC, Ivan95kos commented on src/test/java/org/project/name/online/book/store/controller/CategoryControllerTest.java
> +
line
```suggestion
```

2023-10-11 20:33 UTC, Ivan95kos commented on src/test/java/org/project/name/online/book/store/controller/CategoryControllerTest.java
> +class CategoryControllerTest {
```suggestion
class CategoryControllerIntegrationTest {
```

2023-10-11 20:33 UTC, Ivan95kos commented on src/test/java/org/project/name/online/book/store/repository/BookRepositoryTest.java
> +class BookRepositoryTest {
```suggestion
class BookRepositoryIntegrationTest {
```

2023-10-11 20:33 UTC, Ivan95kos commented on src/test/java/org/project/name/online/book/store/controller/BookControllerTest.java
> +        expected.setCategoryIds(List.of("Test name1"));
it is difficult to read such tests
It is better to transfer all preparation to a private method with the appropriate name
fix it everywhere

2023-10-12 11:18 UTC, kozhukhovsky approved these changes

2023-10-14 07:28 UTC, merged